### Exercise 1 Basic Numpy

(1) Create an array of 10 random integers, from 0-100.

(2) Find the mean and standard deviation of these numbers.  

(3) Create another array of 10 random integers, from 0-100.

(4) Create a new array whose elements are the average of those from
    each of the previous ones.  

(5) Create an array of 10 random floats, from 0-100.

(6) We would expect the mean to be approaximately 50.  Is it?  What's
    the standard deviation?

(7) What are the min and max values?

In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,100, 10)
a

array([ 1,  6, 44, 77, 33, 95, 15, 47,  9, 55])

In [3]:
print(f" mean = {a.mean()}  std = {a.std()}")

 mean = 38.2  std = 29.939271868233536


In [4]:
b  = np.random.randint(0, 100, 10)
b

array([26, 43,  9, 60, 24, 72, 13, 98, 11, 93])

In [5]:
c = np.array([a.mean(), b.mean()])
c

array([38.2, 44.9])

In [10]:
d = np.random.rand( 10)*100
d

array([27.72159405, 75.17633132, 41.20515559, 19.19845995, 79.65038778,
       59.49875184, 72.68249297, 88.95342748, 49.65115912,  7.89265843])

In [11]:
d.mean()

52.1630418537287

In [12]:
d.std()

26.237108023129736

In [13]:
print(f" min= {d.min()}  max = {d.max()}")

 min= 7.8926584259855765  max = 88.95342748400849


### Exercise 2 Indexing

(1) Create an array of 20 random integers from 0 to 100.

(2) Find the largest even number.

(3) Find the mean of the odd numbers.

(4) Create a NumPy array from the first and last odd numbers.

(5) Create an array of 20 floats from 0-1,000.

(6) Find the items that are less than the mean.

(7) Find the items less than mean-std.

In [19]:
a = np.random.randint(0, 100, 20)
a

array([60, 71, 82, 58, 27, 28, 97, 21, 34, 94, 19, 82, 92, 51, 60, 71, 51,
       32, 28, 20])

In [20]:
a[ a%2 == 0].max()

94

In [21]:
a[a%2 != 0].mean()

51.0

In [22]:
b = np.array([a[a%2 != 0].min(), a[a%2 != 0].max()])
b

array([19, 97])

In [23]:
a = np.random.random(20) *1000
a

array([423.262303  , 338.89625069, 921.07645555, 951.17856851,
        72.60681983, 711.68849807, 686.49176282, 411.97902223,
       720.17196286, 188.38543601,  63.65871171, 200.82859998,
       242.51743378, 831.98778607, 426.82591081, 857.65664954,
       744.1553205 , 539.98228376, 613.58403954, 173.24063334])

In [24]:
a[a<a.mean()]

array([423.262303  , 338.89625069,  72.60681983, 411.97902223,
       188.38543601,  63.65871171, 200.82859998, 242.51743378,
       426.82591081, 173.24063334])

In [25]:
a[a<(a.mean() -a.std())]

array([ 72.60681983, 188.38543601,  63.65871171, 200.82859998,
       173.24063334])

### Exercise 3 More indexing

(1) Create a NumPy array of 20 random integers from 0-100.

(2) What's the smallest even number greater than the mean?

(3) Show all numbers either < mean-std or > mean+std.

(4) Show odd numbers < mean and even numbers > mean.

In [26]:
a = np.random.randint(0, 100, 20)
a

array([58, 39, 97, 89, 23, 66, 61, 36, 17, 59, 20,  0, 39, 78, 47, 43, 50,
       30, 47, 71])

In [27]:
a.mean()

48.5

In [28]:
a[((a>a.mean()) * (a%2==0))].min()

50

In [29]:
a[(a<(a.mean()- a.std())) | (a>(a.mean()+a.std()))]

array([97, 89, 23, 17, 20,  0, 78])

In [30]:
a[((a%2 != 0)*(a<a.mean())) * ((a%2 == 0)*(a>a.mean()))] 

array([], dtype=int64)

In [31]:
# no element because there will be no intersection/common element which is greater than mean and less than mean at the same time

### Exercise 4 Assigning via indexes

(1) Create a NumPy array of 40 random integers, from 0-100.

(2) Find all numbers that are within 1 standard deviation of the mean,
    and set them to be equal to the mean.  Has the mean changed?  Has
    the std changed?

(3) Create another NumPy array of 10 random integers, from 0-100.

(4) Set the item at the even indexes to be equal to the items at the odd
    indexes.  So index 0 will get the value at index 1, etc.

In [37]:
a = np.random.randint(0,100, 40)
a

array([52, 92, 66,  0, 72, 88, 66, 61, 12, 62, 89, 18, 65, 83, 16, 62, 56,
       85, 11, 48, 38, 21, 41, 77,  4, 33, 84, 16, 68, 40, 71, 32, 53, 22,
       11,  1, 17, 74, 98, 57])

In [38]:
print(f" mean = {a.mean()}  std = {a.std()}")

 mean = 49.05  std = 28.618132363940177


In [39]:
a[(a>(a.mean() - a.std())) * (a<(a.mean() + a.std()))] = a.mean()
a

array([49, 92, 49,  0, 49, 88, 49, 49, 12, 49, 89, 18, 49, 83, 16, 49, 49,
       85, 11, 49, 49, 49, 49, 49,  4, 49, 84, 16, 49, 49, 49, 49, 49, 49,
       11,  1, 17, 49, 98, 49])

In [41]:
print(f" mean = {a.mean()}  std = {a.std()}")  

 mean = 46.3  std = 25.44916501577213


In [42]:
# yes mean and std has changed

In [43]:
a = np.random.randint(0,100, 10)
a

array([71, 35, 53,  9, 41, 71, 90, 73, 95, 88])

In [46]:
a[::2] = a[1::2]
a

array([35, 35,  9,  9, 71, 71, 73, 73, 88, 88])

### Exercise 5 Data types

(1) Create a NumPy array of 10 random integers from 0-100.

(2) Calculate the mean, which will be a float.

(3) Create an array of type float based on it, and replace the
    outliers (i.e., < mean-std or > mean+std) with the mean.

(4) Create a NumPy array of 20 random floats from 0-100.

(5) Replace those numbers whose int portion is even with the mean.
    (So 20.5 would be replaced, but 21.5 would not be.)

In [47]:
a = np.random.randint(0,100, 10)
a

array([36,  4, 65,  6, 24, 65, 36, 91, 10, 19])

In [48]:
a.mean()

35.6

In [49]:
b = np.array( a[(a<(a.mean()- a.std())) | (a> (a.mean() + a.std()))], dtype=np.float64)
b

array([ 4., 65.,  6., 65., 91.])

In [50]:
c = np.random.rand(20)* 100
c

array([92.78025348, 94.78537978, 41.39134952, 67.83731936, 37.81088809,
        2.48887981, 22.36045581,  1.20542237, 80.26251408, 96.91136031,
       14.27149282, 67.48939104,  9.30428512, 18.86369952, 12.72013353,
       83.30555002, 89.57157728, 52.52102052, 68.58531583,  3.24734063])

In [51]:
c[ c.astype(np.int64)%2 == 0 ] = c.mean()
c

array([47.88568145, 47.88568145, 41.39134952, 67.83731936, 37.81088809,
       47.88568145, 47.88568145,  1.20542237, 47.88568145, 47.88568145,
       47.88568145, 67.48939104,  9.30428512, 47.88568145, 47.88568145,
       83.30555002, 89.57157728, 47.88568145, 47.88568145,  3.24734063])

### Exercise 6 nan

(1) Create a NumPy array of 30 random ints from 0-1000.

(2) Find the numbers that are < mean-std or > mean+std, and set them to
    be nan

(3) Now change those nan values to be the mean of the array's
    elements.

In [52]:
a = np.random.randint(0,1000, 30)
a

array([686, 113, 722, 512, 431, 728, 607, 113, 316, 609, 378, 716, 804,
       159,  41, 637, 564, 352,  92, 873, 944,  25, 999, 635, 396, 777,
        26, 901, 929, 286])

In [53]:
a = a.astype(np.float64)

In [54]:
a[(a<(a.mean()- a.std())) | (a> (a.mean() + a.std()))] =np.nan
a

array([686.,  nan, 722., 512., 431., 728., 607.,  nan, 316., 609., 378.,
       716., 804.,  nan,  nan, 637., 564., 352.,  nan,  nan,  nan,  nan,
        nan, 635., 396., 777.,  nan,  nan,  nan, 286.])

In [55]:
a[np.isnan(a)] = a[~np.isnan(a)].mean()
a

array([686.        , 564.22222222, 722.        , 512.        ,
       431.        , 728.        , 607.        , 564.22222222,
       316.        , 609.        , 378.        , 716.        ,
       804.        , 564.22222222, 564.22222222, 637.        ,
       564.        , 352.        , 564.22222222, 564.22222222,
       564.22222222, 564.22222222, 564.22222222, 635.        ,
       396.        , 777.        , 564.22222222, 564.22222222,
       564.22222222, 286.        ])

### Exercise 7 Multidimensional NumPy

(1) Create a 2-dimensional NumPy array of 45 random integers, from 0-100.

(2) Retrieve the elements at row index 2.

(3) Retrieve the elements at column index 3.

(4) Retrieve the elements at row indexes 1 and 4.

(5) Retrieve the elements at column indexes 1 and 4.

(6) Get the mean of the even numbers in row index 4.

(7) Get the mean of the odd numbers in column index 4.

In [56]:
a = np.random.randint(0,100, [5,9])
a

array([[47, 91, 50, 72, 68, 13, 85, 29, 27],
       [42, 60, 80, 69, 75, 58, 67,  4, 36],
       [74, 42, 12, 20, 26, 61, 37, 48, 74],
       [27, 63, 49, 55, 61, 67, 19, 40, 49],
       [67, 58, 38,  3, 91, 99,  2, 11, 42]])

In [57]:
a[2]

array([74, 42, 12, 20, 26, 61, 37, 48, 74])

In [58]:
a[:,3]

array([72, 69, 20, 55,  3])

In [59]:
a[[1,4],:]

array([[42, 60, 80, 69, 75, 58, 67,  4, 36],
       [67, 58, 38,  3, 91, 99,  2, 11, 42]])

In [60]:
a[:,[1,4]]

array([[91, 68],
       [60, 75],
       [42, 26],
       [63, 61],
       [58, 91]])

In [61]:
a[4][a[4]% 2 == 0].mean()

35.0

In [63]:
a[:,4][a[:,4] % 2 != 0].mean()

75.66666666666667

### Exercise 8 More Multidimensional

(1) Create a 6x6 NumPy array with random integers from 0-100.

(2) What is the mean of each column?

(3) Replace all even numbers in the array with twice their values. (So
    20 will become 40, and 40 will become 80.)

(4) Once again, calculate the mean of each column

(5) Now transpose the array and calculate the mean of each row.  Is it
    the same as you got before?

(6) Now sort each of the columns in the transposed array.  What does
    it look like now?

In [64]:
a = np.random.randint(0,100, [6,6])
a

array([[66, 58, 41,  7, 94, 22],
       [19, 86, 92,  2, 78, 89],
       [89,  6, 95, 28, 24, 17],
       [77, 74, 90, 94, 82, 25],
       [53, 73, 45, 77, 14,  0],
       [91, 81, 87, 10, 74, 98]])

In [65]:
a.mean(axis = 0)

array([65.83333333, 63.        , 75.        , 36.33333333, 61.        ,
       41.83333333])

In [66]:
for  i in range(len(a)):
  for j in range(len(a[i])):
    if a[i][j]%2 == 0:
      a[i][j] *=2
a

array([[132, 116,  41,   7, 188,  44],
       [ 19, 172, 184,   4, 156,  89],
       [ 89,  12,  95,  56,  48,  17],
       [ 77, 148, 180, 188, 164,  25],
       [ 53,  73,  45,  77,  28,   0],
       [ 91,  81,  87,  20, 148, 196]])

In [67]:
a.mean(axis = 0)

array([ 76.83333333, 100.33333333, 105.33333333,  58.66666667,
       122.        ,  61.83333333])

In [68]:
a = a.T
a

array([[132,  19,  89,  77,  53,  91],
       [116, 172,  12, 148,  73,  81],
       [ 41, 184,  95, 180,  45,  87],
       [  7,   4,  56, 188,  77,  20],
       [188, 156,  48, 164,  28, 148],
       [ 44,  89,  17,  25,   0, 196]])

In [69]:
a.mean(axis = 1) 

array([ 76.83333333, 100.33333333, 105.33333333,  58.66666667,
       122.        ,  61.83333333])

In [70]:
# Yes, it is indeed the same as the one we got before

In [71]:
a.sort(axis=0)

In [72]:
a

array([[  7,   4,  12,  25,   0,  20],
       [ 41,  19,  17,  77,  28,  81],
       [ 44,  89,  48, 148,  45,  87],
       [116, 156,  56, 164,  53,  91],
       [132, 172,  89, 180,  73, 148],
       [188, 184,  95, 188,  77, 196]])

# The END